package com.example.aresservicemysql;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.xml.ws.RequestWrapper;

@Controller
@Slf4j
@RequestMapping(path="/admin")
public class HeroController {
    @Autowired // This means to get the bean called heroRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private HeroRepository heroRepository;
    private Hero hero;

    @PostMapping(path="/add")
    public @ResponseBody String addNewUser (
            @RequestParam String firstName,
            @RequestParam String lastName,
            @RequestParam String codeName,
            @RequestParam String email,
            @RequestParam String team
    ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        log.info("Inside PostMapping");
        Hero n = new Hero();
        n.setFirstName(firstName);
        n.setLastName(lastName);
        n.setCodeName(codeName);
        n.setEmail(email);
        n.setTeam(team);
        heroRepository.save(n);

        return "Saved";

    }

}